/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coupon {
  'discountAmountINR' : bigint,
  'code' : string,
  'isActive' : boolean,
  'maxUsesPerUser' : bigint,
}
export interface CustomerProfile {
  'city' : string,
  'name' : string,
  'gmail' : string,
  'address' : string,
  'landmark' : string,
  'phone' : string,
  'pincode' : string,
  'profileComplete' : boolean,
}
export interface DeliveryRule {
  'zoneOrPincode' : string,
  'isDefault' : boolean,
  'chargeINR' : bigint,
}
export interface Order {
  'customerName' : string,
  'status' : string,
  'city' : string,
  'createdAt' : bigint,
  'totalINR' : bigint,
  'razorpayOrderId' : string,
  'address' : string,
  'customerId' : Principal,
  'landmark' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
  'pincode' : string,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Product {
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'discountPriceINR' : bigint,
  'category' : string,
  'priceINR' : bigint,
}
export interface Review {
  'status' : string,
  'createdAt' : bigint,
  'productId' : bigint,
  'comment' : string,
  'customerId' : Principal,
  'rating' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCoupon' : ActorMethod<[Coupon], bigint>,
  'addDeliveryRule' : ActorMethod<[DeliveryRule], bigint>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'approveReview' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[CustomerProfile], undefined>,
  'createOrder' : ActorMethod<
    [
      Array<OrderItem>,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    [] | [bigint]
  >,
  'createRazorpayOrder' : ActorMethod<
    [bigint, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteCoupon' : ActorMethod<[bigint], undefined>,
  'deleteDeliveryRule' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'filterProductsByCategory' : ActorMethod<[string], Array<[bigint, Product]>>,
  'getAllOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getApprovedReviewsForProduct' : ActorMethod<[bigint], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getCoupons' : ActorMethod<[], Array<[bigint, Coupon]>>,
  'getCustomerReviews' : ActorMethod<[], Array<Review>>,
  'getDeletedOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getDeliveryChargeForPincode' : ActorMethod<[string], bigint>,
  'getDeliveryRules' : ActorMethod<[], Array<[bigint, DeliveryRule]>>,
  'getMyOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getMyProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersSortedById' : ActorMethod<[], Array<[bigint, Order]>>,
  'getOrdersSortedByTotal' : ActorMethod<[], Array<[bigint, Order]>>,
  'getPendingOrders' : ActorMethod<[], Array<[bigint, Order]>>,
  'getPendingReviews' : ActorMethod<[], Array<[bigint, Review]>>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<[bigint, Product]>>,
  'getProductsSortedByName' : ActorMethod<[], Array<[bigint, Product]>>,
  'getProductsSortedByPrice' : ActorMethod<[], Array<[bigint, Product]>>,
  'getProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'getRazorpayKeys' : ActorMethod<[], [string, string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'hasCouponBeenUsed' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemCoupon' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'saveCallerUserProfile' : ActorMethod<[CustomerProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<[bigint, Product]>>,
  'setRazorpayKeys' : ActorMethod<[string, string], undefined>,
  'softDeleteOrders' : ActorMethod<[Array<bigint>], boolean>,
  'submitReview' : ActorMethod<
    [bigint, bigint, string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCoupon' : ActorMethod<[bigint, Coupon], undefined>,
  'updateDeliveryRule' : ActorMethod<[bigint, DeliveryRule], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], boolean>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'validateAdminToken' : ActorMethod<[string], boolean>,
  'validateCoupon' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];