/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coupon = IDL.Record({
  'discountAmountINR' : IDL.Nat,
  'code' : IDL.Text,
  'isActive' : IDL.Bool,
  'maxUsesPerUser' : IDL.Nat,
});
export const DeliveryRule = IDL.Record({
  'zoneOrPincode' : IDL.Text,
  'isDefault' : IDL.Bool,
  'chargeINR' : IDL.Nat,
});
export const Product = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'discountPriceINR' : IDL.Nat,
  'category' : IDL.Text,
  'priceINR' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'gmail' : IDL.Text,
  'address' : IDL.Text,
  'landmark' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
  'profileComplete' : IDL.Bool,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalINR' : IDL.Nat,
  'razorpayOrderId' : IDL.Text,
  'address' : IDL.Text,
  'customerId' : IDL.Principal,
  'landmark' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'pincode' : IDL.Text,
});
export const Review = IDL.Record({
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'customerId' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCoupon' : IDL.Func([Coupon], [IDL.Nat], []),
  'addDeliveryRule' : IDL.Func([DeliveryRule], [IDL.Nat], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      ['query'],
    ),
  'approveReview' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([CustomerProfile], [], []),
  'createOrder' : IDL.Func(
      [
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
  'createRazorpayOrder' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
  'deleteDeliveryRule' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'filterProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'getAllOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getApprovedReviewsForProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getCoupons' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Coupon))], ['query']),
  'getCustomerReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getDeletedOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getDeliveryChargeForPincode' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getDeliveryRules' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, DeliveryRule))],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Order))], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersSortedById' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getOrdersSortedByTotal' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getPendingOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
      ['query'],
    ),
  'getPendingReviews' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Review))],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'getProductsSortedByName' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'getProductsSortedByPrice' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'getProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getRazorpayKeys' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'hasCouponBeenUsed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
  'searchProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'setRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'softDeleteOrders' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'submitReview' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCoupon' : IDL.Func([IDL.Nat, Coupon], [], []),
  'updateDeliveryRule' : IDL.Func([IDL.Nat, DeliveryRule], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'validateCoupon' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coupon = IDL.Record({
    'discountAmountINR' : IDL.Nat,
    'code' : IDL.Text,
    'isActive' : IDL.Bool,
    'maxUsesPerUser' : IDL.Nat,
  });
  const DeliveryRule = IDL.Record({
    'zoneOrPincode' : IDL.Text,
    'isDefault' : IDL.Bool,
    'chargeINR' : IDL.Nat,
  });
  const Product = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'discountPriceINR' : IDL.Nat,
    'category' : IDL.Text,
    'priceINR' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'gmail' : IDL.Text,
    'address' : IDL.Text,
    'landmark' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
    'profileComplete' : IDL.Bool,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalINR' : IDL.Nat,
    'razorpayOrderId' : IDL.Text,
    'address' : IDL.Text,
    'customerId' : IDL.Principal,
    'landmark' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'pincode' : IDL.Text,
  });
  const Review = IDL.Record({
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'customerId' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCoupon' : IDL.Func([Coupon], [IDL.Nat], []),
    'addDeliveryRule' : IDL.Func([DeliveryRule], [IDL.Nat], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        ['query'],
      ),
    'approveReview' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([CustomerProfile], [], []),
    'createOrder' : IDL.Func(
        [
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
    'createRazorpayOrder' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
    'deleteDeliveryRule' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'filterProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'getAllOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getApprovedReviewsForProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getCoupons' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Coupon))],
        ['query'],
      ),
    'getCustomerReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getDeletedOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getDeliveryChargeForPincode' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getDeliveryRules' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, DeliveryRule))],
        ['query'],
      ),
    'getMyOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersSortedById' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getOrdersSortedByTotal' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getPendingOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Order))],
        ['query'],
      ),
    'getPendingReviews' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Review))],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'getProductsSortedByName' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'getProductsSortedByPrice' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'getProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getRazorpayKeys' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'hasCouponBeenUsed' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
    'searchProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'setRazorpayKeys' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'softDeleteOrders' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'submitReview' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCoupon' : IDL.Func([IDL.Nat, Coupon], [], []),
    'updateDeliveryRule' : IDL.Func([IDL.Nat, DeliveryRule], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'validateCoupon' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };